apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: web-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-nginx
  template:
    metadata:
      labels:
        app: web-nginx
    spec:
      containers:
        - name: nginx
          image: lab-nginx:latest
          imagePullPolicy: Never   # usa la imagen local de Minikube
          ports:
            - containerPort: 80
